steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up JDK
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '17'

  - name: Set up Android SDK
    uses: android-actions/setup-android@v3

  - name: Grant execute permission for Gradle wrapper
    run: chmod +x ./gradlew

  - name: Cache Gradle dependencies
    uses: actions/cache@v3
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

  - name: Build Release APK
    run: ./gradlew assembleRelease

  - name: Upload APK to GitHub Release
    uses: softprops/action-gh-release@v2
    with:
      files: app/build/outputs/apk/release/app-release.apk
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
